name: Node.js Package

# on:
#   release:
#     types: [created]

on:
  push:
    branches:
      - actions-test

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: koonpeng/romi-js
    steps:
      - uses: actions/checkout@v2
        with:
          path: colcon_ws/src
      - uses: actions/checkout@v2
        with:
          repository: osrf/rmf_core
          path: colcon_ws/src
      - uses: actions/checkout@v2
        with:
          repository: osrf/traffic_editor
          path: colcon_ws/src
      - run: pip3 install jinja2
      - run: cd ${{env.GITHUB_WORKSPACE}}/colcon_ws && colcon build --packages-up-to romi-js-core-interfaces

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
