name: Node.js Package

# on:
#   release:
#     types: [created]

on:
  push:
    branches:
      - actions-test

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: koonpeng/romi-js
    steps:
      - uses: actions/checkout@v2
        with:
          path: colcon_ws/src/romi-js-core-interfaces
      - uses: actions/checkout@v2
        with:
          repository: osrf/rmf_core
          path: colcon_ws/src/rmf_core
      - uses: actions/checkout@v2
        with:
          repository: osrf/traffic_editor
          path: colcon_ws/src/traffic_editor
      - run: pip3 install jinja2
      - run: /entrypoint.sh bash -c "cd $GITHUB_WORKSPACE/colcon_ws && colcon build --packages-up-to romi-js-core-interfaces"
      - run: /entrypoint.sh bash -c ". $GITHUB_WORKSPACE/colcon_ws/build/install/setup.bash && cd $GITHUB_WORKSPACE/colcon_ws/src/romi-js-core-interfaces && npm publish --dry-run"
